package com.car.sales.company.models;

public enum NombreNotificacion {
    COMPRADOR_PRIMERA_OFERTA, COMPRADOR_ACEPTA_OFERTA, COMPRADOR_RETIRA_OFERTA, VEHICULO_EXPIRADO,
    NUEVO_VEHICULO_EN_VENTA, VENDEDOR_CONTRAOFERTA, VENDEDOR_ACEPTA_OFERTA, VENDEDOR_DECLINA_OFERTA, VEHICULO_NO_DISPONIBLE
}
